name: schulz
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7744373509194702
title: what it is
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfeaf4'
    - '#bfccd4'
    - '#a0adb3'
    - '#0c110b'
    - '#263435'
  brandStrength: 0.3125
  lightness: 0.45735409506596625
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
