name: schulz
favicon: null
layout_spectrum: 0.9096282599493861
typography_spectrum: 0.7744373509194702
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.40061059477739036
  lightness: 0.45735409506596625
  saturation: 0.2990323551930487
  rhythmicContrast: 0.23855711752548814
purpose: []
